version: '3'
services:
  # whatever name of service won't work because you extends and change it name for ex, docker-compose up -d --build api
  api:
    extends:
      file: docker-compose-api.yml
      service: backend

  db:
    extends:
      file: docker-compose-database.yml
      service: database

# have to set it again because it can't see
volumes: # for storing value on container (can call service in backend part)
  information-database: # define volume name
    driver: local # use only current pc